// Mocks generated by Mockito from annotations
// in flutter_clean_architecture/test/features/university/domain/usercases/search_universities_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:flutter_clean_architecture/core/network/api_response.dart'
    as _i2;
import 'package:flutter_clean_architecture/features/university/domain/entities/params/search_university_params.dart'
    as _i6;
import 'package:flutter_clean_architecture/features/university/domain/entities/university.dart'
    as _i5;
import 'package:flutter_clean_architecture/features/university/domain/repositories/university_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UniversityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUniversityRepository extends _i1.Mock
    implements _i3.UniversityRepository {
  @override
  _i4.Future<_i2.ApiResponse<List<_i5.University>>> search({
    required _i6.SearchUniversityParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {#params: params}),
            returnValue:
                _i4.Future<_i2.ApiResponse<List<_i5.University>>>.value(
                  _FakeApiResponse_0<List<_i5.University>>(
                    this,
                    Invocation.method(#search, [], {#params: params}),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.ApiResponse<List<_i5.University>>>.value(
                  _FakeApiResponse_0<List<_i5.University>>(
                    this,
                    Invocation.method(#search, [], {#params: params}),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<List<_i5.University>>>);
}
