// Mocks generated by Mockito from annotations
// in flutter_clean_architecture/test/features/university/presentation/bloc/pages/university_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:flutter_clean_architecture/core/network/api_response.dart'
    as _i3;
import 'package:flutter_clean_architecture/features/country/domain/entities/country.dart'
    as _i10;
import 'package:flutter_clean_architecture/features/country/domain/repositories/country_repository.dart'
    as _i4;
import 'package:flutter_clean_architecture/features/country/domain/usecases/get_all_country_usecase.dart'
    as _i9;
import 'package:flutter_clean_architecture/features/university/domain/entities/params/search_university_params.dart'
    as _i8;
import 'package:flutter_clean_architecture/features/university/domain/entities/university.dart'
    as _i7;
import 'package:flutter_clean_architecture/features/university/domain/repositories/university_repository.dart'
    as _i2;
import 'package:flutter_clean_architecture/features/university/domain/usecases/search_universities_usecase.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUniversityRepository_0 extends _i1.SmartFake
    implements _i2.UniversityRepository {
  _FakeUniversityRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResponse_1<T> extends _i1.SmartFake
    implements _i3.ApiResponse<T> {
  _FakeApiResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountryRepository_2 extends _i1.SmartFake
    implements _i4.CountryRepository {
  _FakeCountryRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchUniversitiesUsercase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchUniversitiesUsercase extends _i1.Mock
    implements _i5.SearchUniversitiesUsercase {
  MockSearchUniversitiesUsercase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UniversityRepository get universityRepository =>
      (super.noSuchMethod(
            Invocation.getter(#universityRepository),
            returnValue: _FakeUniversityRepository_0(
              this,
              Invocation.getter(#universityRepository),
            ),
          )
          as _i2.UniversityRepository);

  @override
  _i6.Future<_i3.ApiResponse<List<_i7.University>>> call({
    required _i8.SearchUniversityParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i6.Future<_i3.ApiResponse<List<_i7.University>>>.value(
                  _FakeApiResponse_1<List<_i7.University>>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i6.Future<_i3.ApiResponse<List<_i7.University>>>);
}

/// A class which mocks [GetAllCountryUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCountryUsecase extends _i1.Mock
    implements _i9.GetAllCountryUsecase {
  MockGetAllCountryUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CountryRepository get countryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#countryRepository),
            returnValue: _FakeCountryRepository_2(
              this,
              Invocation.getter(#countryRepository),
            ),
          )
          as _i4.CountryRepository);

  @override
  _i6.Future<List<_i10.Country>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i6.Future<List<_i10.Country>>.value(<_i10.Country>[]),
          )
          as _i6.Future<List<_i10.Country>>);
}
